const text =
  "\n" +
  "\n" +
  "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque vitae magna mi. Suspendisse condimentum magna lacus, ac gravida nunc sollicitudin lobortis. Nullam sit amet tortor nec est commodo mattis quis a velit. Mauris tincidunt justo ex, porta lacinia justo convallis ac. Duis convallis ullamcorper scelerisque. Morbi pellentesque finibus lectus, eget hendrerit magna. Phasellus at tortor ex. Suspendisse diam tortor, eleifend blandit ante consequat, posuere efficitur tortor. Nulla gravida mi ac sem iaculis, a aliquet justo feugiat. Morbi iaculis, tortor et porttitor molestie, purus leo porttitor erat, vitae euismod est erat nec nulla. Pellentesque quis tempor justo, id dapibus eros. Mauris elementum, sapien eget facilisis varius, tellus arcu placerat turpis, in bibendum lectus nunc quis lectus.\n" +
  "\n" +
  "In molestie metus mauris, vel tincidunt massa iaculis ac. Aenean consectetur consectetur risus quis dignissim. Vestibulum lacinia risus odio, sed mollis sem tristique non. Donec in molestie metus. Mauris vulputate porta malesuada. Fusce convallis diam sed vehicula blandit. Quisque quis ante auctor, lobortis orci eu, sagittis lorem. Phasellus tellus mi, maximus sed nulla vel, faucibus interdum odio. Integer facilisis justo dictum metus faucibus, eu auctor velit semper. Etiam metus orci, dignissim commodo ex vitae, condimentum mattis justo. Donec ac vulputate mi. Aenean sed enim tortor. Phasellus scelerisque est tempor fringilla consectetur. Nam laoreet at diam iaculis hendrerit.\n" +
  "\n" +
  "Mauris non finibus risus. Aliquam erat volutpat. Phasellus sit amet nulla tellus. Cras semper leo in magna ullamcorper rhoncus. Pellentesque ut sem neque. Maecenas iaculis blandit tellus id feugiat. Ut tempus, diam et elementum bibendum, eros erat condimentum nulla, sit amet euismod neque lacus eget lacus. Donec pellentesque justo quis sollicitudin eleifend. Donec velit nibh, sollicitudin quis sagittis vel, semper sit amet enim. Nulla sit amet nibh sit amet ligula malesuada vestibulum. Pellentesque luctus sapien ac diam bibendum rutrum. Vestibulum maximus purus enim, a consectetur mauris ultricies eget. Vivamus egestas nisi et porta mollis. Morbi velit quam, vestibulum nec feugiat et, tempus in turpis. Suspendisse varius, ex ac blandit aliquam, dui leo lobortis libero, et scelerisque nisi augue cursus sem.\n" +
  "\n" +
  "Etiam commodo, risus in convallis finibus, massa lacus vulputate tellus, nec finibus turpis quam a massa. Duis eu aliquet augue. Nunc posuere diam eget vulputate auctor. Vestibulum non congue ipsum. Praesent tempor ex purus, eu venenatis ligula malesuada id. Duis tincidunt pulvinar mattis. Sed sit amet ipsum sit amet ipsum iaculis sollicitudin id in elit. Mauris interdum placerat purus eget sagittis. Mauris eleifend cursus mollis.\n" +
  "\n" +
  "In iaculis, quam ut pellentesque finibus, ex lorem cursus felis, ut pharetra ligula ligula eget ante. Suspendisse tempor ligula quis vehicula dapibus. Vestibulum eget massa eget nibh aliquet luctus at eget est. Duis sit amet orci sit amet tortor semper volutpat. Donec porta quam maximus rhoncus sollicitudin. Quisque iaculis purus molestie felis accumsan eleifend. Nunc a lobortis sem. Etiam venenatis non justo a posuere. Suspendisse posuere fermentum porttitor. Donec eget magna tristique, aliquet dui ut, porta justo. Integer posuere, odio id mattis elementum, eros risus lacinia elit, id ultricies diam metus sit amet mauris. Vivamus dignissim, velit in pretium cursus, diam arcu tincidunt ligula, quis faucibus mi ipsum vel mauris. Nam tempus mollis ornare. Phasellus magna enim, facilisis eu malesuada non, rhoncus non ex. ";

export default text;

export const blurbText = "This is some blurb text i'm writing for a post. I talk about what I will talk about in the actual post, but only a summary of it."
